### ISSUE TITLE
New link 

### ISSUE THREAD

**Issue by AbhishakeL** [microsud/Tools-Microbiome-Analysis#10]
Don't know if new links are added here, but I found 
[metaSPARSim](https://gitlab.com/sysbiobig/metasparsim ) to be a useful tool..

**Comment by microsud** [comment]
Hi @AbhishakeL Thanks for the suggestions. I will add it in the next update.

Best wishes,
Sudarshan

**Comment by microsud** [comment]
This suggestion is added to the website https://microsud.github.io/Tools-Microbiome-Analysis/CHANGES.html
