### ISSUE TITLE
More refs

### ISSUE THREAD

**Issue by SvetlanaUP** [microsud/Tools-Microbiome-Analysis#15]
Hi Sudarshan, this list is excellent! Thank you.

I've been curating my own "Control/Contamination" ref list and here I'm sending you the ones that you might add:

- Laboratory contamination over time during low-biomass sample analysis (Weyrich et al., 2019) https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.13011
- Consistent and correctable bias in metagenomic sequencing experiments (McLaren et al., 2019) https://elifesciences.org/articles/46923
- Community profiling of the urinary microbiota: considerations for low-biomass samples (Karstens et al., 2018) https://www.nature.com/articles/s41585-018-0104-z
- Identification and removal of contaminating microbial DNA from PCR reagents: impact on low-biomass microbiome analyses (Stinson et al., 2018) https://sfamjournals.onlinelibrary.wiley.com/doi/full/10.1111/lam.13091
- Simple statistical identification and removal of contaminant sequences in marker-gene and metagenomics data (Davis et al., 2018) https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0605-2
- Recognizing the reagent microbiome (de Goffau et al., 2018) https://www.nature.com/articles/s41564-018-0202-y
- Contamination in Low Microbial Biomass Microbiome Studies: Issues and Recommendations (Eisenhofer et al., 2018) https://www.cell.com/action/showPdf?pii=S0966-842X%2818%2930253-1
- Optimizing methods and dodging pitfalls in microbiome research (Kim et al., 2017) https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-017-0267-5

Best,
Svetlana

**Comment by microsud** [comment]
Thanks!! I will add these. Also is your list public, I can link them here?

**Comment by SvetlanaUP** [comment]
The "Control/Contamination" list is not public, but other microbiome related lists are https://twitter.com/svetlana_up/status/1418516358355169281
Might be interesting to you.

Once again thanks for compiling and sharing this one!

Best, 
Svetlana

**Comment by microsud** [comment]
Thanks! These should be [visible](https://microsud.github.io/Tools-Microbiome-Analysis/CHANGES.html) on the [website](https://microsud.github.io/Tools-Microbiome-Analysis/TutorialsResources.html) after GH has built it.
